import { jsPDF } from "jspdf";
import { AnalysisResult } from "../services/geminiService";
import { getSamhitaData } from "../constants";

const getFormatFromDataUrl = (dataUrl: string): string => {
  if (typeof dataUrl !== 'string') return "JPEG";
  if (dataUrl.startsWith("data:image/png") || dataUrl.includes(".png")) return "PNG";
  if (dataUrl.startsWith("data:image/webp") || dataUrl.includes(".webp")) return "WEBP";
  if (dataUrl.startsWith("data:image/gif") || dataUrl.includes(".gif")) return "GIF";
  return "JPEG";
};

export const generateClinicalPDF = (
  result: AnalysisResult & { images?: string[] },
  userProfile: any,
  fallbackDoshaPercentages?: { 
    Vata: number; 
    Pitta: number; 
    Kapha: number;
    counts?: { Vata: number; Pitta: number; Kapha: number }
  },
  images?: string[]
) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  let y = 75;
  let currentPage = 1;

  // Header and Footer draw helpers
  const drawPageHeader = () => {
    doc.setFillColor(24, 24, 27); // stone-900
    doc.rect(0, 0, pageWidth, 20, "F");
    
    doc.setFillColor(16, 185, 129); // emerald-500
    doc.rect(0, 20, pageWidth, 1, "F");
    
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text("KUSHTHA AI - CLINICAL REPORT (CONTINUED)", margin, 12);
    
    doc.setTextColor(163, 163, 163);
    doc.setFont("helvetica", "normal");
    doc.text(`PATIENT: ${userProfile.name?.toUpperCase() || 'N/A'}`, pageWidth - margin - 60, 12);
  };

  const drawFooter = () => {
    // Elegant separator line instead of solid black banner to prevent overlaps
    doc.setDrawColor(16, 185, 129, 0.4); // emerald with low opacity
    doc.line(margin, pageHeight - 20, pageWidth - margin, pageHeight - 20);

    doc.setTextColor(115, 115, 115); // stone-500
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text("This report is generated by Kushtha AI specifically for wellness assessment and educational purposes.", pageWidth / 2, pageHeight - 14, { align: "center" });
    doc.text("It is recommended to consult a certified Vaidya for actual medical treatment.", pageWidth / 2, pageHeight - 9, { align: "center" });
    
    // Page number
    doc.setFont("helvetica", "bold");
    doc.text(`Page ${currentPage}`, pageWidth - margin, pageHeight - 11, { align: "right" });
  };

  const checkPageOverflow = (heightNeeded: number) => {
    if (y + heightNeeded > pageHeight - 25) {
      drawFooter();
      doc.addPage();
      currentPage++;
      y = 35;
      drawPageHeader();
    }
  };

  // ==================== PAGE 1 INITIAL HEADER ====================
  // Header Background
  doc.setFillColor(24, 24, 27); // stone-900
  doc.rect(0, 0, pageWidth, 55, "F");
  
  // Decorative Accent bar
  doc.setFillColor(16, 185, 129); // emerald-500
  doc.rect(0, 55, pageWidth, 2, "F");

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(28);
  doc.text("KUSHTHA AI", margin, 25);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(16, 185, 129); // emerald-500
  doc.text("VIRTUAL AYURVEDIC DERMATOLOGY UNIT", margin, 35);

  // Date
  doc.setTextColor(163, 163, 163); // stone-400
  doc.setFontSize(10);
  const dateStr = new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' });
  doc.text(`SESSION DATE: ${dateStr}`, pageWidth - margin - 55, 25);
  
  // Patient Info Section (New Card Style)
  doc.setFillColor(248, 250, 252); // extremely light slate
  doc.roundedRect(margin, y, pageWidth - (margin * 2), 42, 3, 3, "F");
  
  y += 10;
  doc.setTextColor(24, 24, 27);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("PATIENT BIOMETRICS", margin + 10, y);
  
  y += 8;
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text(`NAME: ${userProfile.name?.toUpperCase() || 'N/A'}`, margin + 10, y);
  doc.text(`AGE/SEX: ${userProfile.age || 'N/A'} / ${userProfile.sex || 'N/A'}`, margin + 100, y);

  y += 6;
  doc.setFont("helvetica", "normal");
  doc.text(`REGION: ${userProfile.state || 'N/A'}`, margin + 10, y);
  doc.text(`OCCUPATION: ${userProfile.occupation || 'N/A'}`, margin + 100, y);

  y += 6;
  doc.text(`CHRONICITY: ${userProfile.chronicity || 'N/A'}`, margin + 10, y);
  doc.text(`FAMILY HISTORY: ${userProfile.familyHistory || 'N/A'}`, margin + 100, y);
  
  // Diagnostic Summary
  y += 20;
  const kushtaData = getSamhitaData(result.specificKushtha);
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(16, 185, 129); // emerald
  doc.text("CLINICAL VINISHCHAYA (AYURVEDIC DIAGNOSIS)", margin, y);
  
  y += 4;
  doc.setDrawColor(16, 185, 129, 0.2);
  doc.line(margin, y, pageWidth - margin, y);

  y += 12;
  doc.setFontSize(11);
  doc.setTextColor(24, 24, 27);
  doc.text("PRIMARY KUSHTHA:", margin, y);
  doc.setTextColor(5, 150, 105); // darker emerald
  doc.setFontSize(13);
  doc.text(result.specificKushtha || "Sama Twak (Healthy Skin)", margin + 60, y);

  y += 8;
  doc.setFontSize(10);
  doc.setTextColor(120, 113, 108); // stone-500
  doc.text("AYUSH TM2 CODE:", margin, y);
  doc.setTextColor(24, 24, 27);
  doc.text(result.tm2 || (kushtaData?.tm2 || "N/A"), margin + 60, y);

  y += 6;
  doc.setTextColor(120, 113, 108);
  doc.text("PRIMARY DOSHA:", margin, y);
  doc.setTextColor(5, 150, 105);
  doc.text(result.primaryDosha || "Sama (Balanced)", margin + 60, y);
  y += 4;

  // ==================== LESION IMAGES SECTION ====================
  const clinicalImages = images || result.images || [];
  const validImages = clinicalImages.filter(img => typeof img === 'string' && img.length > 50);

  if (validImages.length > 0) {
    const imagesToDraw = validImages.slice(0, 3); // show up to 3 collected angles
    const imgHeight = 40;
    const imgWidth = 50;
    const spacing = 8;
    const boxHeight = imgHeight + 12;

    checkPageOverflow(boxHeight + 20);

    y += 12;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(16, 185, 129); // emerald
    doc.text("CLINICAL IMAGERY (LESION EVIDENCE)", margin, y);
    
    y += 4;
    doc.setDrawColor(16, 185, 129, 0.2);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;

    imagesToDraw.forEach((imgData, index) => {
      const imgX = margin + (index * (imgWidth + spacing));
      
      // Draw background border box
      doc.setDrawColor(229, 231, 235); // light gray border
      doc.setFillColor(250, 250, 249); // light stone-50 background card
      doc.roundedRect(imgX - 2, y - 2, imgWidth + 4, imgHeight + 4, 1.5, 1.5, "F");
      doc.roundedRect(imgX - 2, y - 2, imgWidth + 4, imgHeight + 4, 1.5, 1.5, "S");
      
      try {
        const format = getFormatFromDataUrl(imgData);
        doc.addImage(imgData, format, imgX, y, imgWidth, imgHeight);
      } catch (err) {
        doc.setFont("helvetica", "italic");
        doc.setFontSize(8);
        doc.setTextColor(120, 113, 108);
        doc.text("Attachment Corrupted", imgX + 5, y + (imgHeight / 2));
        console.error("Error drawing image in PDF", err);
      }
    });

    y += imgHeight + 10;
  }

  // Modern Clinical Correlation (DermNet NZ)
  if (result.modernClinicalCorrelation) {
    const headerText = "INDEPENDENT MODERN CLINICAL IMPRESSION";
    const bodyText = `Clinical Assessment: ${result.modernClinicalCorrelation}\nICD-11 Code Reference: ${result.icd11 || 'N/A'}\n\nDisclaimer Notice: Modern and Ayurvedic clinical methodologies represent completely separate diagnostic systems. No direct correlation or joint diagnostic equivalence is represented.`;
    
    const splitBody = doc.splitTextToSize(bodyText, pageWidth - (margin * 2) - 10);
    const boxHeight = (splitBody.length * 5) + 15;
    
    // Check overflow and position safely
    checkPageOverflow(boxHeight + 20);
    y += 12;
    doc.setFillColor(239, 246, 255); // blue-50
    doc.roundedRect(margin, y - 5, pageWidth - (margin * 2), boxHeight, 3, 3, "F");
    
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(30, 64, 175); // blue-800
    doc.text(headerText, margin + 5, y);
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(59, 130, 246); // clear blue
    doc.text(splitBody, margin + 5, y + 6);
    y += boxHeight + 5;
  }

  // ==================== DIFFERENTIAL DIAGNOSIS SECTION ====================
  const predictionsList = result.predictions || [
    {
      specificKushtha: result.specificKushtha,
      modernClinicalCorrelation: result.modernClinicalCorrelation,
      confidenceScore: result.confidenceScore
    }
  ];

  checkPageOverflow(30 + (predictionsList.length * 15));

  y += 12;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(16, 185, 129); // emerald
  doc.text("CLINICAL DIFFERENTIAL DIAGNOSIS (CANDIDATES)", margin, y);

  y += 4;
  doc.setDrawColor(16, 185, 129, 0.2);
  doc.line(margin, y, pageWidth - margin, y);
  y += 6;

  // Table Headers
  doc.setFontSize(8.5);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(120, 113, 108);
  doc.text("RANK", margin, y);
  doc.text("AYURVEDIC DIFFERENTIAL", margin + 15, y);
  doc.text("MODERN CORRELATION", margin + 80, y);
  doc.text("CONFIDENCE", pageWidth - margin - 30, y);
  y += 4;

  predictionsList.forEach((pred, index) => {
    const isPrimary = index === 0;
    const ayurvedaText = pred.specificKushtha || "N/A";
    const modernText = (pred.modernClinicalCorrelation || "N/A").replace(/^Modern:\s*/i, '');
    
    const ayurLines = doc.splitTextToSize(ayurvedaText, 60).length;
    const modBoxW = pageWidth - margin - 80 - 35; // approx 55 width
    const modernLines = doc.splitTextToSize(modernText, modBoxW).length;
    const maxLines = Math.max(ayurLines, modernLines, 1);
    const rowHeight = (maxLines * 4.5) + 6;

    checkPageOverflow(rowHeight + 6);
    
    // Highlight background for Primary Match
    if (isPrimary) {
      doc.setFillColor(236, 253, 245); // emerald-50
      // Pad out a neat box
      doc.rect(margin - 2, y - 2, (pageWidth - margin * 2) + 4, rowHeight, "F");
    }

    // Left accent border indicator
    doc.setDrawColor(isPrimary ? 16 : 229, isPrimary ? 185 : 231, isPrimary ? 129 : 235);
    doc.setLineWidth(1.5);
    doc.line(margin - 2, y - 2, margin - 2, y - 2 + rowHeight);

    // Rank
    doc.setFont("helvetica", isPrimary ? "bold" : "normal");
    doc.setFontSize(9);
    doc.setTextColor(isPrimary ? 16 : 120, isPrimary ? 185 : 113, isPrimary ? 129 : 108);
    doc.text(isPrimary ? "PRI" : `#${index + 1}`, margin, y + 3);
    
    // Ayurveda Column
    if (isPrimary) {
      doc.setTextColor(5, 150, 105); // emerald-600 (Primary Match highlight)
    } else {
      doc.setTextColor(24, 24, 27); // stone-900
    }
    doc.text(ayurvedaText, margin + 15, y + 3, { maxWidth: 60 });
    
    // Modern Column
    if (isPrimary) {
      doc.setTextColor(30, 64, 175); // blue-800
    } else {
      doc.setTextColor(68, 64, 60); // stone-700
    }
    doc.text(modernText, margin + 80, y + 3, { maxWidth: modBoxW });
    
    // Confidence Rating & Progress bar
    const confPct = Math.round(pred.confidenceScore);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(16, 185, 129);
    doc.text(`${confPct}%`, pageWidth - margin - 30, y + 3);
    
    doc.setFillColor(242, 242, 242);
    doc.rect(pageWidth - margin - 20, y, 20, 3, "F");
    doc.setFillColor(16, 185, 129);
    doc.rect(pageWidth - margin - 20, y, (Math.min(confPct, 100) / 100) * 20, 3, "F");
    
    y += rowHeight + 2;
  });

  // Reset line thickness for downstream report borders
  doc.setLineWidth(1);

  // Near-tie warnings & low clinical confidence advisory boxes
  const topPrediction = predictionsList[0];
  const secondPrediction = predictionsList[1];
  const topScore = topPrediction && typeof topPrediction.confidenceScore === 'number' ? topPrediction.confidenceScore : 0;
  const secondScore = secondPrediction && typeof secondPrediction.confidenceScore === 'number' ? secondPrediction.confidenceScore : 0;
  const isLowConfidence = topPrediction ? topScore < 50 : false;
  const isNearTie = (topPrediction && secondPrediction)
    ? Math.abs(topScore - secondScore) <= 10
    : false;

  if (isNearTie || isLowConfidence) {
    const warningText = isNearTie 
      ? "CLINICAL ADVISORY: Candidates exhibit strongly resembling visual profiles (near-tie situation). Direct tactile palpation or Qualified manual dermoscopy is highlighted for differentiation."
      : "CLINICAL ADVISORY: Combined primary diagnostic confidence of candidates remains low. Broad/overlapping clinical features might be contributing.";
    
    const splitWarning = doc.splitTextToSize(warningText, pageWidth - (margin * 2) - 10);
    const warnBoxHeight = (splitWarning.length * 4.5) + 8;
    
    checkPageOverflow(warnBoxHeight + 8);
    
    doc.setFillColor(254, 242, 242); // red-50
    doc.roundedRect(margin, y - 5, pageWidth - (margin * 2), warnBoxHeight, 2, 2, "F");
    
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8.5);
    doc.setTextColor(185, 28, 28); // red-700
    doc.text(splitWarning, margin + 5, y);
    y += warnBoxHeight + 5;
  }

  y += 12;
  doc.setFontSize(11);
  doc.setTextColor(24, 24, 27);
  doc.text("DOSHIC DOMINANCE:", margin, y);
  doc.text(result.primaryDosha || "N/A", margin + 60, y);

  // Split and render description with safety page height check
  const splitDescription = doc.splitTextToSize(result.description || "", pageWidth - (margin * 2));
  const descHeightNeeded = (splitDescription.length * 6) + 16;
  checkPageOverflow(descHeightNeeded);

  y += 12;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(68, 64, 60); // stone-700
  doc.text(splitDescription, margin, y);
  y += (splitDescription.length * 6) + 12;

  // Doshic Balance
  let Vata = 0;
  let Pitta = 0;
  let Kapha = 0;
  let VataCount: number | undefined = undefined;
  let PittaCount: number | undefined = undefined;
  let KaphaCount: number | undefined = undefined;

  // Prioritize absolute fallback (calculated from questionnaire symptom markers) to avoid proportional overrides
  if (fallbackDoshaPercentages && typeof fallbackDoshaPercentages.Vata === 'number') {
    Vata = fallbackDoshaPercentages.Vata;
    Pitta = fallbackDoshaPercentages.Pitta;
    Kapha = fallbackDoshaPercentages.Kapha;
    if (fallbackDoshaPercentages.counts) {
      VataCount = fallbackDoshaPercentages.counts.Vata;
      PittaCount = fallbackDoshaPercentages.counts.Pitta;
      KaphaCount = fallbackDoshaPercentages.counts.Kapha;
    }
  } else if (result.doshaPercentages && typeof result.doshaPercentages.Vata === 'number') {
    Vata = result.doshaPercentages.Vata;
    Pitta = result.doshaPercentages.Pitta;
    Kapha = result.doshaPercentages.Kapha;
    const pctsObj = result.doshaPercentages as any;
    if (pctsObj.counts) {
      VataCount = pctsObj.counts.Vata;
      PittaCount = pctsObj.counts.Pitta;
      KaphaCount = pctsObj.counts.Kapha;
    }
  } else {
    const pDosha = result.primaryDosha || 'Sama';
    if (pDosha === 'Vata') {
      Vata = 60; Pitta = 20; Kapha = 20;
    } else if (pDosha === 'Pitta') {
      Vata = 20; Pitta = 60; Kapha = 20;
    } else if (pDosha === 'Kapha') {
      Vata = 20; Pitta = 20; Kapha = 60;
    } else if (pDosha.includes('Vata') && pDosha.includes('Pitta')) {
      Vata = 45; Pitta = 45; Kapha = 10;
    } else if (pDosha.includes('Kapha') && pDosha.includes('Pitta')) {
      Vata = 10; Pitta = 45; Kapha = 45;
    } else if (pDosha.includes('Kapha') && pDosha.includes('Vata')) {
      Vata = 45; Pitta = 10; Kapha = 45;
    } else {
      Vata = 33.3; Pitta = 33.3; Kapha = 33.4;
    }
  }

  // Check overflow before starting the Dosha Breakdown section
  checkPageOverflow(65);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(24, 24, 27);
  doc.text("DOSHA PERCENTAGES & DOMINANCY BREAKDOWN", margin, y);
  y += 10;
  
  const barMaxWidth = 100;

  let dominanceDef = "Sama (Balanced)";
  if (Vata > Pitta && Vata > Kapha) dominanceDef = "Vata Dominance";
  else if (Pitta > Vata && Pitta > Kapha) dominanceDef = "Pitta Dominance";
  else if (Kapha > Vata && Kapha > Pitta) dominanceDef = "Kapha Dominance";

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(5, 150, 105);
  doc.text(`PRIMARY PATTERN: ${dominanceDef.toUpperCase()}`, margin, y);
  y += 10;

  const doshesForPdf = [
    { name: "VATA COMPONENT", pct: Vata, count: VataCount, max: 10, color: { r: 245, g: 158, b: 11 } },
    { name: "PITTA COMPONENT", pct: Pitta, count: PittaCount, max: 7, color: { r: 244, g: 63, b: 94 } },
    { name: "KAPHA COMPONENT", pct: Kapha, count: KaphaCount, max: 9, color: { r: 16, g: 185, b: 129 } }
  ];

  doshesForPdf.forEach((d) => {
    // Draw Bar Background
    doc.setFillColor(242, 242, 242);
    doc.roundedRect(margin, y - 5, pageWidth - (margin * 2), 11, 1, 1, "F");
    
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(120, 113, 108);
    
    const labelText = d.count !== undefined ? `${d.name} (${d.count} of ${d.max} positive markers)` : d.name;
    doc.text(labelText, margin + 5, y + 2);
    
    // Draw Active Bar Filled
    doc.setFillColor(d.color.r, d.color.g, d.color.b);
    if (d.pct > 0) {
      doc.rect(margin + 68, y - 1, (Math.min(d.pct, 100) / 100) * (barMaxWidth - 10), 3, "F");
    }
    doc.text(`${Math.round(d.pct)}%`, margin + 73 + (Math.min(d.pct, 100) / 100) * (barMaxWidth - 10), y + 2);
    
    y += 14;
  });

  // Clinical Markers
  const lakshanas = result.lakshanasFound || [];
  const markersHeightNeeded = lakshanas.length > 0 ? 30 : 0;
  
  if (markersHeightNeeded > 0) {
    checkPageOverflow(markersHeightNeeded);

    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(16, 185, 129);
    doc.text("IDENTIFIED VISUAL LAKSHANAS", margin, y);
    y += 10;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(68, 64, 60);

    let lx = margin;
    let ly = y;
    lakshanas.forEach((l) => {
      doc.setFillColor(240, 253, 244); // emerald-50
      const textWidth = doc.getTextWidth(l) + 10;
      if (lx + textWidth > pageWidth - margin) {
        lx = margin;
        ly += 8;
      }
      // Ensure we don't bleed off the bottom page edge during inline rendering
      if (ly > pageHeight - 25) {
        drawFooter();
        doc.addPage();
        currentPage++;
        ly = 35;
        lx = margin;
        drawPageHeader();
      }
      doc.roundedRect(lx, ly - 5, textWidth, 7, 1, 1, "F");
      doc.setTextColor(5, 150, 105); // emerald-600
      doc.text(l.toUpperCase(), lx + 5, ly);
      lx += textWidth + 5;
    });
    
    y = ly + 20;
  }

  // Recommendations Card (Dynamic Placement and Box Sizing)
  const recs = result.recommendations || [];
  if (recs.length > 0) {
    let recsHeight = 15; // padding top and header
    const bulletLines: any[] = [];
    
    recs.slice(0, 5).forEach((r) => {
      const splitLines = doc.splitTextToSize(`• ${r}`, pageWidth - (margin * 2) - 10);
      bulletLines.push(splitLines);
      recsHeight += (splitLines.length * 5);
    });
    recsHeight += 8; // padding bottom

    // Check boundary
    checkPageOverflow(recsHeight + 10);

    // Draw yellow tint box
    doc.setFillColor(254, 252, 232); // amber-50
    doc.rect(margin, y - 8, pageWidth - (margin * 2), recsHeight, "F");
    
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(180, 83, 9); // amber-700
    doc.text("PATHYA-APATHYA (RECOMMENDATIONS)", margin + 5, y);
    y += 10;
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(24, 24, 27);
    
    bulletLines.forEach((lines) => {
      doc.text(lines, margin + 5, y);
      y += (lines.length * 5);
    });
    
    y += 15; // Margin beneath recommendation box
  }

  // Reference Text Section (Wrapped and formatted elegantly with safety margin)
  const rawReferenceText = `REFERENCE: ${result.ayurvedicContext || "Charaka Samhita, Kushtha Chikitsa Adhyaya"}`;
  doc.setFont("helvetica", "italic");
  doc.setTextColor(16, 185, 129);
  doc.setFontSize(9);
  
  const splitRef = doc.splitTextToSize(rawReferenceText, pageWidth - (margin * 2));
  const refHeightNeeded = (splitRef.length * 5) + 15;

  checkPageOverflow(refHeightNeeded);

  doc.text(splitRef, margin, y);
  y += (splitRef.length * 5) + 10;

  // Print final footer for the last page
  drawFooter();

  // Save the clinical report
  const fileName = `Kushtha_Report_${userProfile.name?.replace(/\s+/g, '_') || 'Patient'}.pdf`;
  doc.save(fileName);
};
